# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from widgets.image_widget import ImageWidget
from widgets.info_widget import InfoWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")

        MainWindow.resize(1600, 1200)

        self.centralwidget = QtWidgets.QSplitter(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.videoswidget = QtWidgets.QListView()
        self.videoswidget.setMinimumWidth(350)
        self.centralwidget.addWidget(self.videoswidget)

        self.displaywidget = ImageWidget()
        self.centralwidget.addWidget(self.displaywidget)

        self.infowidget = InfoWidget()
        self.infowidget.setMinimumWidth(350)
        self.centralwidget.addWidget(self.infowidget)

        self.centralwidget.setStretchFactor(0, 0)
        self.centralwidget.setStretchFactor(1, 1)
        self.centralwidget.setStretchFactor(2, 0)

        # self.pushButton1 = QtWidgets.QPushButton()
        # self.pushButton1.setObjectName("pushButton")

        # self.centralwidget.addWidget(self.pushButton1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # self.update_style()

        self.retranslateUi(MainWindow)

        # self.pushButton1.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # file.triggered[QtWidgets.QAction].connect(self.process_action)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "电视机回收质检系统"))
        # self.pushButton1.setText(_translate("Exit", "退出"))

    def update_style(self):
        background_color = 'rgb(252, 252, 252)'
        main_style = '''
            QSplitter {
                background-color: rgb(252, 252, 252);
                padding: 5px;
            }
        '''
        self.centralwidget.setStyleSheet(main_style)

        videos_style = '''
            QListView {
                background-color: rgb(252, 252, 252);
                border: 0px;
                font-size: 10pt;
            }
        '''
        self.videoswidget.setStyleSheet(videos_style)

        display_style = '''
            ImageWidget {
                font-size: 10pt;
            }
            QLabel {
                font-size: 10pt;
            }
        '''
        self.displaywidget.setStyleSheet(display_style)

        info_style = '''
            InfoWidget {
                background-color: rgb(252, 252, 252);
                font-size: 10pt;
            }
            QLabel, QLineEdit, QDateTimeEdit, QTextEdit {
                font-size: 10pt;
                background-color: rgb(252, 252, 252);
            },
            QLineEdit {
                border-style: solid;
                border-top-width: 0px;
                border-right-width: 0px;
                border-left-width: 0px;
            }
        '''
        self.infowidget.setStyleSheet(info_style)


if __name__ == "__main__":
    import sys
    # 实例化，传参
    app = QtWidgets.QApplication(sys.argv)
    # 创建对象
    Form = QtWidgets.QMainWindow()
    # 创建ui，引用UI_MainWindow类
    ui = Ui_MainWindow() #这个是类名，名字根据自定义的情况变化
    # 调用UI_MainWindow类的setupUi函数，创建初始组件
    ui.setupUi(Form)
    # 创建窗口
    Form.show()
    # 进入程序的主循环，并通过exit函数确保主循环安全结束(该释放资源的一定要释放)
    sys.exit(app.exec_())
